/**
 * Smart Canteen Management Platform
 * Comprehensive Seed Data & Menu Variety
 */

const INITIAL_DATA = {
  // Current logged in student
  currentUser: {
    id: "usr_101",
    name: "Rahul Sharma",
    studentId: "CS-2023-8941",
    email: "rahul.sharma@campus.edu",
    phone: "+91 98765 43210",
    department: "Computer Science & Eng.",
    walletBalance: 450.00,
    role: "student",
    avatar: "AV",
    favorites: ["item_1", "item_4", "item_13", "item_19"]
  },

  // Food Categories
  categories: [
    { id: "all", name: "All Items", icon: "" },
    { id: "specials", name: "Today's Specials", icon: "⭐" },
    { id: "breakfast", name: "Breakfast", icon: "" },
    { id: "lunch", name: "Lunch & Meals", icon: "" },
    { id: "snacks", name: "Snacks & Bites", icon: "" },
    { id: "fastfood", name: "Fast Food", icon: "" },
    { id: "beverages", name: "Beverages", icon: "" },
    { id: "desserts", name: "Desserts & Sweets", icon: "" }
  ],

  // Expanded Menu Variety (24 Delicious Campus Favorites)
  menuItems: [
    // --- LUNCH & MEALS ---
    {
      id: "item_1",
      name: "Hyderabadi Chicken Dum Biryani",
      category: "lunch",
      price: 130,
      description: "Fragrant long-grain basmati rice layered with tender marinated chicken, boiled egg, saffron, served with cool cucumber raita and mirchi ka salan.",
      isVeg: false,
      isSpecial: true,
      tag: "Chef's Special",
      available: true,
      stockQuantity: 42,
      rating: 4.9,
      reviewsCount: 210,
      prepTimeMinutes: 10,
      image: "assets/chicken_biryani.jpg",
      ingredients: ["Basmati Rice", "Chicken", "Spices", "Yogurt", "Egg"],
      calories: "580 kcal",
      spiceLevel: "Medium Spicy"
    },
    {
      id: "item_2",
      name: "Deluxe Veg Thali Meals",
      category: "lunch",
      price: 85,
      description: "Complete wholesome platter: Paneer butter masala, yellow dal tadka, steamed basmati rice, 2 hot butter rotis, cucumber salad, and sweet gulab jamun.",
      isVeg: true,
      isSpecial: false,
      tag: "Best Value",
      available: true,
      stockQuantity: 65,
      rating: 4.8,
      reviewsCount: 245,
      prepTimeMinutes: 5,
      image: "assets/veg_meals.jpg",
      ingredients: ["Basmati Rice", "Paneer", "Lentils", "Whole Wheat", "Tomatoes"],
      calories: "520 kcal",
      spiceLevel: "Mild"
    },
    {
      id: "item_3",
      name: "Sizzling Paneer Fried Rice",
      category: "lunch",
      price: 95,
      description: "Wok-tossed long-grain rice with golden pan-seared paneer cubes, crunchy bell peppers, carrots, spring onions, and savory Asian sauces.",
      isVeg: true,
      isSpecial: true,
      tag: "Today's Special",
      available: true,
      stockQuantity: 30,
      rating: 4.7,
      reviewsCount: 118,
      prepTimeMinutes: 12,
      image: "assets/paneer_fried_rice.jpg",
      ingredients: ["Basmati Rice", "Paneer", "Bell Peppers", "Spring Onions", "Soy Sauce"],
      calories: "460 kcal",
      spiceLevel: "Medium"
    },
    {
      id: "item_9",
      name: "Punjabi Dal Makhani Rice Bowl",
      category: "lunch",
      price: 80,
      description: "Slow-cooked black lentils simmered overnight with butter and fresh cream, served on a bed of fluffy cumin jeera rice with pickled onions.",
      isVeg: true,
      isSpecial: false,
      tag: "Comfort Food",
      available: true,
      stockQuantity: 35,
      rating: 4.8,
      reviewsCount: 92,
      prepTimeMinutes: 6,
      image: "assets/veg_meals.jpg",
      ingredients: ["Black Lentils", "Butter", "Cream", "Jeera Rice", "Spices"],
      calories: "490 kcal",
      spiceLevel: "Mild"
    },
    {
      id: "item_10",
      name: "Campus Rajma Chawal Special",
      category: "lunch",
      price: 75,
      description: "Tender red kidney beans cooked in aromatic onion-tomato gravy, served with steamed basmati rice, papad, and fresh mint chutney.",
      isVeg: true,
      isSpecial: false,
      tag: "Student Favorite",
      available: true,
      stockQuantity: 40,
      rating: 4.7,
      reviewsCount: 134,
      prepTimeMinutes: 5,
      image: "assets/veg_meals.jpg",
      ingredients: ["Kidney Beans", "Rice", "Tomatoes", "Onions", "Coriander"],
      calories: "450 kcal",
      spiceLevel: "Medium"
    },
    {
      id: "item_11",
      name: "Chicken Tikka Rice Bowl",
      category: "lunch",
      price: 120,
      description: "Char-grilled smoky chicken tikka chunks served over spiced turmeric pilaf with mint yoghurt sauce, pickled onions, and lemon wedge.",
      isVeg: false,
      isSpecial: true,
      tag: "High Protein",
      available: true,
      stockQuantity: 25,
      rating: 4.9,
      reviewsCount: 160,
      prepTimeMinutes: 10,
      image: "assets/chicken_biryani.jpg",
      ingredients: ["Chicken Breast", "Yogurt", "Tandoori Spices", "Basmati Rice"],
      calories: "530 kcal",
      spiceLevel: "Spicy"
    },

    // --- BREAKFAST ---
    {
      id: "item_4",
      name: "Crispy Masala Dosa",
      category: "breakfast",
      price: 60,
      description: "Thin golden crispy crepe made from fermented lentil batter, filled with savory spiced potato masala, served with fresh coconut chutney and piping hot sambar.",
      isVeg: true,
      isSpecial: false,
      tag: "Morning Hit",
      available: true,
      stockQuantity: 45,
      rating: 4.9,
      reviewsCount: 310,
      prepTimeMinutes: 8,
      image: "assets/masala_dosa.jpg",
      ingredients: ["Rice Batter", "Potatoes", "Coconut", "Sambar Lentils"],
      calories: "320 kcal",
      spiceLevel: "Mild"
    },
    {
      id: "item_12",
      name: "Steamed Idli & Medu Vada Combo",
      category: "breakfast",
      price: 50,
      description: "Two pillow-soft steamed rice idlis and one crispy golden medu vada, served with South Indian sambar and roasted peanut coconut chutney.",
      isVeg: true,
      isSpecial: false,
      tag: "Light & Healthy",
      available: true,
      stockQuantity: 50,
      rating: 4.8,
      reviewsCount: 180,
      prepTimeMinutes: 4,
      image: "assets/masala_dosa.jpg",
      ingredients: ["Urad Dal", "Rice", "Curry Leaves", "Coconut", "Mustard Seeds"],
      calories: "280 kcal",
      spiceLevel: "Mild"
    },
    {
      id: "item_13",
      name: "Stuffed Aloo Paratha with Curd",
      category: "breakfast",
      price: 55,
      description: "Two whole wheat griddled flatbreads stuffed with spicy mashed potato and fresh coriander, served with home-style curd and tangy mango pickle.",
      isVeg: true,
      isSpecial: false,
      tag: "Hearty Breakfast",
      available: true,
      stockQuantity: 35,
      rating: 4.8,
      reviewsCount: 142,
      prepTimeMinutes: 8,
      image: "assets/masala_dosa.jpg",
      ingredients: ["Whole Wheat Flour", "Potatoes", "Butter", "Curd", "Green Chillies"],
      calories: "390 kcal",
      spiceLevel: "Medium"
    },
    {
      id: "item_14",
      name: "Indori Poha with Crunchy Sev",
      category: "breakfast",
      price: 35,
      description: "Steamed flattened rice tempered with mustard seeds, curry leaves, roasted peanuts, turmeric, topped with ratlami sev and fresh lemon juice.",
      isVeg: true,
      isSpecial: false,
      tag: "Quick Morning",
      available: true,
      stockQuantity: 40,
      rating: 4.6,
      reviewsCount: 95,
      prepTimeMinutes: 3,
      image: "assets/samosa_chai.jpg",
      ingredients: ["Poha", "Peanuts", "Mustard Seeds", "Sev", "Lemon"],
      calories: "240 kcal",
      spiceLevel: "Mild"
    },

    // --- SNACKS & QUICK BITES ---
    {
      id: "item_5",
      name: "Crispy Samosa with Masala Chai",
      category: "snacks",
      price: 40,
      description: "Two hot flaky pastry triangles stuffed with spiced cumin potatoes and peas, paired with mint chutney, sweet tamarind dip, and steaming ginger cardamom chai.",
      isVeg: true,
      isSpecial: false,
      tag: "Evening Classic",
      available: true,
      stockQuantity: 28,
      rating: 4.9,
      reviewsCount: 220,
      prepTimeMinutes: 3,
      image: "assets/samosa_chai.jpg",
      ingredients: ["Flour", "Potatoes", "Peas", "Tea Leaves", "Ginger", "Cardamom"],
      calories: "340 kcal",
      spiceLevel: "Medium"
    },
    {
      id: "item_7",
      name: "Double Egg Chicken Kathi Roll",
      category: "snacks",
      price: 75,
      description: "Flaky pan-fried paratha layered with twin beaten eggs, spiced shredded chicken, crunchy sliced onions, chaat masala, and spicy green chutney.",
      isVeg: false,
      isSpecial: false,
      tag: "Grab & Go",
      available: true,
      stockQuantity: 26,
      rating: 4.8,
      reviewsCount: 155,
      prepTimeMinutes: 7,
      image: "assets/chicken_biryani.jpg",
      ingredients: ["Paratha", "Eggs", "Chicken", "Onions", "Green Chutney"],
      calories: "440 kcal",
      spiceLevel: "Spicy"
    },
    {
      id: "item_15",
      name: "Butter Pav Bhaji Platter",
      category: "snacks",
      price: 70,
      description: "Thick mashed vegetable curry cooked with special spices and generous dollop of butter, served with two toasted butter pavs, diced onions, and lemon.",
      isVeg: true,
      isSpecial: true,
      tag: "Campus Sensation",
      available: true,
      stockQuantity: 32,
      rating: 4.8,
      reviewsCount: 188,
      prepTimeMinutes: 6,
      image: "assets/samosa_chai.jpg",
      ingredients: ["Mixed Veggies", "Butter", "Pav Buns", "Pav Bhaji Masala"],
      calories: "420 kcal",
      spiceLevel: "Spicy"
    },
    {
      id: "item_16",
      name: "Grilled Paneer Tikka Wrap",
      category: "snacks",
      price: 65,
      description: "Soft whole wheat tortilla wrapped around marinated tandoori paneer cubes, crisp lettuce, capsicum, and creamy garlic herb dressing.",
      isVeg: true,
      isSpecial: false,
      tag: "Protein Wrap",
      available: true,
      stockQuantity: 22,
      rating: 4.7,
      reviewsCount: 84,
      prepTimeMinutes: 7,
      image: "assets/paneer_fried_rice.jpg",
      ingredients: ["Paneer", "Tortilla Wrap", "Bell Peppers", "Garlic Herb Sauce"],
      calories: "380 kcal",
      spiceLevel: "Medium"
    },

    // --- FAST FOOD & STREET ---
    {
      id: "item_17",
      name: "Crispy Peri-Peri French Fries",
      category: "fastfood",
      price: 55,
      description: "Golden crispy skin-on potato fries tossed in spicy African peri-peri seasoning, served hot with creamy cheese dip.",
      isVeg: true,
      isSpecial: false,
      tag: "Crunchy Snack",
      available: true,
      stockQuantity: 35,
      rating: 4.7,
      reviewsCount: 120,
      prepTimeMinutes: 5,
      image: "assets/samosa_chai.jpg",
      ingredients: ["Potatoes", "Peri-Peri Seasoning", "Cheese Dip"],
      calories: "310 kcal",
      spiceLevel: "Spicy"
    },
    {
      id: "item_18",
      name: "Classic Chicken Cheese Burger",
      category: "fastfood",
      price: 85,
      description: "Crispy fried chicken patty topped with melted cheddar cheese slice, fresh lettuce, tomato, and house burger relish on a toasted sesame bun.",
      isVeg: false,
      isSpecial: true,
      tag: "Crowd Favorite",
      available: true,
      stockQuantity: 24,
      rating: 4.9,
      reviewsCount: 175,
      prepTimeMinutes: 8,
      image: "assets/chicken_biryani.jpg",
      ingredients: ["Chicken Patty", "Brioche Bun", "Cheddar Cheese", "Lettuce", "Sauce"],
      calories: "480 kcal",
      spiceLevel: "Mild"
    },
    {
      id: "item_19",
      name: "Veg Hakka Noodles & Manchurian Combo",
      category: "fastfood",
      price: 80,
      description: "Wok-tossed noodles with shredded cabbage, carrots, bell peppers, paired with crispy vegetable manchurian balls in spicy dark gravy.",
      isVeg: true,
      isSpecial: false,
      tag: "Desi Chinese",
      available: true,
      stockQuantity: 28,
      rating: 4.8,
      reviewsCount: 140,
      prepTimeMinutes: 9,
      image: "assets/paneer_fried_rice.jpg",
      ingredients: ["Noodles", "Cabbage", "Manchurian Balls", "Soy Sauce", "Chilli Sauce"],
      calories: "450 kcal",
      spiceLevel: "Medium Spicy"
    },
    {
      id: "item_20",
      name: "Steamed Chicken Momos (6 pcs)",
      category: "fastfood",
      price: 70,
      description: "Tender thin-crust Himalayan dumplings filled with juicy minced chicken, ginger, and scallions, served with spicy red schezwan dip.",
      isVeg: false,
      isSpecial: false,
      tag: "Street Style",
      available: true,
      stockQuantity: 30,
      rating: 4.9,
      reviewsCount: 195,
      prepTimeMinutes: 6,
      image: "assets/chicken_biryani.jpg",
      ingredients: ["Minced Chicken", "Flour Wrap", "Garlic", "Red Schezwan Sauce"],
      calories: "290 kcal",
      spiceLevel: "Extra Spicy"
    },

    // --- BEVERAGES & SHAKES ---
    {
      id: "item_6",
      name: "Chilled Fresh Lime Mint Soda",
      category: "beverages",
      price: 30,
      description: "Freshly squeezed Meyer lemons blended with sparkling soda, crushed ice, garden mint leaves, roasted cumin, and black salt.",
      isVeg: true,
      isSpecial: false,
      tag: "Cool Refresher",
      available: true,
      stockQuantity: 55,
      rating: 4.7,
      reviewsCount: 165,
      prepTimeMinutes: 3,
      image: "assets/lime_juice.jpg",
      ingredients: ["Meyer Lemons", "Soda Water", "Mint", "Black Salt"],
      calories: "60 kcal",
      spiceLevel: "Tangy & Fizzy"
    },
    {
      id: "item_8",
      name: "Thick Cold Coffee with Ice Cream",
      category: "beverages",
      price: 65,
      description: "Creamy slow-brewed iced coffee blended with full-cream milk and cocoa, topped with a generous scoop of vanilla ice cream and chocolate drizzle.",
      isVeg: true,
      isSpecial: true,
      tag: "Best Seller",
      available: true,
      stockQuantity: 38,
      rating: 4.9,
      reviewsCount: 280,
      prepTimeMinutes: 4,
      image: "assets/lime_juice.jpg",
      ingredients: ["Brewed Coffee", "Milk", "Vanilla Ice Cream", "Chocolate Sauce"],
      calories: "280 kcal",
      spiceLevel: "Sweet & Creamy"
    },
    {
      id: "item_21",
      name: "Alphonso Mango Lassi",
      category: "beverages",
      price: 45,
      description: "Rich blended yoghurt drink infused with real Alphonso mango pulp, green cardamom powder, and topped with sliced roasted pistachios.",
      isVeg: true,
      isSpecial: false,
      tag: "Summer Hit",
      available: true,
      stockQuantity: 30,
      rating: 4.8,
      reviewsCount: 110,
      prepTimeMinutes: 3,
      image: "assets/lime_juice.jpg",
      ingredients: ["Yogurt", "Mango Pulp", "Pistachios", "Cardamom"],
      calories: "210 kcal",
      spiceLevel: "Sweet"
    },
    {
      id: "item_22",
      name: "Special Masala Cutting Chai",
      category: "beverages",
      price: 15,
      description: "Authentic campus cutting tea brewed with fresh crushed ginger, green cardamom, cloves, cinnamon, and rich milk.",
      isVeg: true,
      isSpecial: false,
      tag: "Energy Booster",
      available: true,
      stockQuantity: 80,
      rating: 4.9,
      reviewsCount: 320,
      prepTimeMinutes: 2,
      image: "assets/samosa_chai.jpg",
      ingredients: ["Assam Tea Leaves", "Milk", "Ginger", "Cardamom", "Cinnamon"],
      calories: "85 kcal",
      spiceLevel: "Aromatic Spiced"
    },

    // --- DESSERTS & SWEETS ---
    {
      id: "item_23",
      name: "Hot Gulab Jamun with Rabri",
      category: "desserts",
      price: 45,
      description: "Two melt-in-mouth golden khoya dumplings soaked in saffron-rose sugar syrup, served warm with rich thickened rabri and chopped almonds.",
      isVeg: true,
      isSpecial: true,
      tag: "Sweet Treat",
      available: true,
      stockQuantity: 25,
      rating: 4.9,
      reviewsCount: 145,
      prepTimeMinutes: 3,
      image: "assets/veg_meals.jpg",
      ingredients: ["Khoya", "Sugar Syrup", "Rabri", "Rose Water", "Almonds"],
      calories: "310 kcal",
      spiceLevel: "Sweet"
    },
    {
      id: "item_24",
      name: "Fudge Chocolate Brownie Sundae",
      category: "desserts",
      price: 65,
      description: "Warm dense Belgian chocolate walnut brownie served with a scoop of vanilla ice cream, hot fudge sauce, and roasted nuts.",
      isVeg: true,
      isSpecial: false,
      tag: "Choco Delight",
      available: true,
      stockQuantity: 20,
      rating: 4.9,
      reviewsCount: 175,
      prepTimeMinutes: 4,
      image: "assets/lime_juice.jpg",
      ingredients: ["Belgian Cocoa", "Walnuts", "Vanilla Ice Cream", "Chocolate Fudge"],
      calories: "390 kcal",
      spiceLevel: "Rich Chocolate"
    }
  ],

  // Expanded Inventory Ingredients (Matching the expanded menu)
  inventory: [
    { id: "inv_1", name: "Basmati & Sona Masoori Rice", category: "Grains", quantity: 50, unit: "kg", minThreshold: 20, status: "Available", lastUpdated: "Today, 10:30 AM" },
    { id: "inv_2", name: "Fresh Farm Chicken", category: "Poultry", quantity: 18, unit: "kg", minThreshold: 12, status: "Available", lastUpdated: "Today, 08:00 AM" },
    { id: "inv_3", name: "Fresh Dairy Paneer", category: "Dairy", quantity: 22, unit: "kg", minThreshold: 8, status: "Available", lastUpdated: "Today, 09:15 AM" },
    { id: "inv_4", name: "Fresh Red Tomatoes", category: "Vegetables", quantity: 14, unit: "kg", minThreshold: 10, status: "Available", lastUpdated: "Today, 11:00 AM" },
    { id: "inv_5", name: "Refined Sunflower Cooking Oil", category: "Oils", quantity: 16, unit: "L", minThreshold: 10, status: "Available", lastUpdated: "Today, 07:30 AM" },
    { id: "inv_6", name: "Whole Wheat Atta & Maida", category: "Grains", quantity: 35, unit: "kg", minThreshold: 15, status: "Available", lastUpdated: "Yesterday" },
    { id: "inv_7", name: "Assam Tea Leaves & Spices Mix", category: "Dry Goods", quantity: 8.5, unit: "kg", minThreshold: 4, status: "Available", lastUpdated: "Today, 08:45 AM" },
    { id: "inv_8", name: "Fresh Yellow Lemons & Mint", category: "Produce", quantity: 60, unit: "pcs", minThreshold: 25, status: "Available", lastUpdated: "Today, 09:00 AM" },
    { id: "inv_9", name: "Full Cream Dairy Milk", category: "Dairy", quantity: 40, unit: "L", minThreshold: 15, status: "Available", lastUpdated: "Today, 06:00 AM" },
    { id: "inv_10", name: "Vanilla Ice Cream Tubs", category: "Frozen", quantity: 12, unit: "tubs", minThreshold: 5, status: "Available", lastUpdated: "Today, 07:00 AM" }
  ],

  // Active & Past Orders
  orders: [
    {
      id: "ord_1042",
      tokenNumber: "A1042",
      userId: "usr_101",
      userName: "Rahul Sharma",
      userPhone: "+91 98765 43210",
      items: [
        { itemId: "item_1", name: "Hyderabadi Chicken Dum Biryani", price: 130, quantity: 1, isVeg: false },
        { itemId: "item_6", name: "Chilled Fresh Lime Mint Soda", price: 30, quantity: 1, isVeg: true }
      ],
      subtotal: 160,
      discount: 16,
      total: 144,
      paymentMethod: "Campus Wallet",
      paymentStatus: "Paid",
      orderStatus: "PREPARING",
      orderType: "Classroom Delivery",
      deliveryType: "classroom",
      classroomDetails: {
        block: "Block B (Computer Science & IT)",
        room: "Room 304",
        instructions: "2nd row from front, next to projector",
        phone: "+91 98765 43210",
        timing: "Immediate (~15-20 min)"
      },
      deliveryFee: 0,
      pickupTime: "Block B • Room 304",
      placedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
      queuePosition: 2,
      estimatedWaitMins: 6,
      notes: "Classroom Delivery: Room 304 (Block B). Raita packed separately"
    },
    {
      id: "ord_1038",
      tokenNumber: "A1038",
      userId: "usr_102",
      userName: "Priya Patel",
      userPhone: "+91 91234 56789",
      items: [
        { itemId: "item_2", name: "Deluxe Veg Thali Meals", price: 85, quantity: 1, isVeg: true },
        { itemId: "item_21", name: "Alphonso Mango Lassi", price: 45, quantity: 1, isVeg: true }
      ],
      subtotal: 130,
      discount: 13,
      total: 117,
      paymentMethod: "UPI (Google Pay)",
      paymentStatus: "Paid",
      orderStatus: "READY",
      orderType: "Counter Pickup",
      deliveryType: "pickup",
      pickupTime: "Counter 2 (Now)",
      placedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      queuePosition: 0,
      estimatedWaitMins: 0,
      notes: ""
    },
    {
      id: "ord_1037",
      tokenNumber: "A1037",
      userId: "usr_103",
      userName: "Arjun Mehta",
      userPhone: "+91 99887 76655",
      items: [
        { itemId: "item_3", name: "Sizzling Paneer Fried Rice", price: 95, quantity: 2, isVeg: true }
      ],
      subtotal: 190,
      discount: 19,
      total: 171,
      paymentMethod: "Campus Wallet",
      paymentStatus: "Paid",
      orderStatus: "COLLECTED",
      orderType: "Pre-Order",
      pickupTime: "12:45 PM",
      placedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
      queuePosition: 0,
      estimatedWaitMins: 0,
      notes: "Make it spicy!"
    },
    {
      id: "ord_1035",
      tokenNumber: "A1035",
      userId: "usr_101",
      userName: "Rahul Sharma",
      userPhone: "+91 98765 43210",
      items: [
        { itemId: "item_4", name: "Crispy Masala Dosa", price: 60, quantity: 1, isVeg: true },
        { itemId: "item_5", name: "Crispy Samosa with Masala Chai", price: 40, quantity: 1, isVeg: true }
      ],
      subtotal: 100,
      discount: 10,
      total: 90,
      paymentMethod: "Campus Wallet",
      paymentStatus: "Paid",
      orderStatus: "COLLECTED",
      orderType: "Immediate",
      pickupTime: "Yesterday",
      placedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
      queuePosition: 0,
      estimatedWaitMins: 0,
      hasFeedback: true,
      rating: 5,
      feedbackComment: "Dosa was crispy and chai was piping hot!"
    }
  ],

  // Student Reviews
  feedbackList: [
    {
      id: "fb_1",
      userName: "Rahul Sharma",
      tokenNumber: "A1035",
      ratingFood: 5,
      ratingService: 5,
      ratingValue: 5,
      comment: "Dosa was very crisp and chai was piping hot! No waiting in line.",
      createdAt: "Yesterday, 4:20 PM",
      reply: "Thank you Rahul! Glad you enjoyed the breakfast combo."
    },
    {
      id: "fb_2",
      userName: "Ananya Deshmukh",
      tokenNumber: "A1024",
      ratingFood: 5,
      ratingService: 5,
      ratingValue: 5,
      comment: "Chicken Biryani is top tier on campus. The pre-ordering saved 20 minutes before our 1 PM lecture.",
      createdAt: "Yesterday, 1:45 PM",
      reply: "Thanks Ananya! Pre-ordering is designed exactly for lecture breaks."
    },
    {
      id: "fb_3",
      userName: "Karthik Raja",
      tokenNumber: "A1019",
      ratingFood: 4,
      ratingService: 5,
      ratingValue: 5,
      comment: "Prompt token notification on mobile. Easy UPI payment.",
      createdAt: "2 days ago",
      reply: "Appreciate your feedback Karthik!"
    }
  ],

  // Notifications
  notifications: [
    {
      id: "notif_1",
      title: "Order In Preparation ‍",
      message: "Order #A1042 is now cooking in the central kitchen. Est. ready time: 6 mins.",
      time: "5 mins ago",
      read: false,
      type: "order"
    },
    {
      id: "notif_2",
      title: "Today's Chef Specials ⭐",
      message: "Paneer Fried Rice & Chicken Dum Biryani are hot on the stove today!",
      time: "1 hour ago",
      read: false,
      type: "promo"
    },
    {
      id: "notif_3",
      title: "Payment Confirmed",
      message: "₹144.00 deducted from Campus Wallet for Order #A1042.",
      time: "15 mins ago",
      read: true,
      type: "payment"
    }
  ]
};

window.INITIAL_DATA = INITIAL_DATA;
